// Custom persona runner.
// Executes a user-defined persona against all eligible projects.
// Uses the same Claude ask() interface as built-in personas.
// Custom personas always run with the same scoped tool set as built-ins
// (text-only, no shell exec, no file writes outside worktree).

import { execSync } from 'node:child_process';
import { ask, askWithImages } from './claude.js';
import { getScreenshots } from './screenshot-cache.js';
import { checkDuplicate, checkRejectionMatch } from './dedup.js';
import { fetchRejections, formatRejectionHistory } from './rejection-history.js';
import { createRunLogger, sanitizeError } from './run-logger.js';
import { assignClusters } from './cluster.js';
import { scoreProposal } from './scoreProposal.js';
import { FILTER_REASONS } from './filter-reasons.js';
import { sanitizeFocusPrompt, sanitizeSystemPrompt } from './custom-personas-config.js';
import { scanFiles, formatFileBatch } from './files.js';

function log(personaId, msg) {
  const ts = new Date().toISOString().replace('T', ' ').slice(0, 19);
  console.log(`[${ts}] [${personaId}] ${msg}`);
}

/**
 * Build the analysis prompt for a custom persona.
 * Incorporates the project's advisorContext, focus areas, and rejection history.
 *
 * @param {object} persona - Validated persona definition
 * @param {string} projectContext - Project advisorContext from Firestore
 * @param {string} [rejectionHistoryBlock] - Formatted rejection history block
 * @returns {string}
 */
function buildPrompt(persona, projectContext, rejectionHistoryBlock, focusPrompt) {
  const parts = [];

  // SECURITY (DK-306): sanitize user-controlled advisorContext before interpolating into the prompt.
  // sanitizeSystemPrompt() strips <system>, </system>, and <| delimiters that could be used for
  // prompt injection while preserving intentional newlines in multi-line project descriptions.
  const safeProjectContext = sanitizeSystemPrompt(projectContext || '');
  if (safeProjectContext?.trim()) {
    parts.push('## Project Context');
    parts.push(safeProjectContext.trim());
    parts.push('');
  }

  if (persona.focusAreas?.length > 0) {
    parts.push('## Focus Areas');
    parts.push(persona.focusAreas.map(fa => `- ${fa}`).join('\n'));
    parts.push('');
  }

  if (rejectionHistoryBlock) {
    parts.push(rejectionHistoryBlock);
    parts.push('');
    parts.push('Do NOT propose ideas similar to the rejected ones above.');
    parts.push('');
  }

  parts.push(`You are reviewing this project. Based on your focus areas and the project context above, identify the most important issues or improvements.

Respond with a JSON array of objects with this shape:
{
  "type": "bug" | "feature",
  "title": "Short ticket title (max 80 chars)",
  "description": "Clear explanation of the issue or opportunity",
  "recommendation": "Specific actionable recommendation",
  "priority": "high" | "medium" | "low"
}

Only include items that are genuinely important — not theoretical edge cases or minor nits.
If nothing significant is found, return an empty array [].
Respond ONLY with valid JSON — no prose, no markdown fences.`);

  // DK-321: Append user hint under an explicit header — clearly separated from system instructions.
  // Never concatenate inline with system instructions. The header signals to the model that
  // this is a one-time user override, not part of the core task definition.
  if (focusPrompt) {
    parts.push(`\n\n---\nUser context (one-time override):\n${focusPrompt}`);
  }

  return parts.join('\n');
}

/**
 * Parse the Claude response into a list of proposals.
 *
 * @param {string} raw
 * @param {string} personaId
 * @returns {Array}
 */
function parseProposals(raw, personaId) {
  try {
    const cleaned = raw.replace(/^```[a-z]*\n?/gm, '').replace(/```$/gm, '').trim();
    const parsed = JSON.parse(cleaned);
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    log(personaId, 'Failed to parse response as JSON — skipping');
    return [];
  }
}

/**
 * Build the ticket description for a custom persona proposal.
 *
 * @param {object} proposal
 * @param {object} persona
 * @returns {string}
 */
function buildTicketDescription(proposal, persona) {
  const parts = [];
  parts.push('## Description');
  parts.push(proposal.description || '');
  parts.push('');
  if (proposal.recommendation) {
    parts.push('## Recommendation');
    parts.push(proposal.recommendation);
    parts.push('');
  }
  if (proposal.priority) {
    parts.push(`**Priority:** ${proposal.priority}`);
    parts.push('');
  }
  parts.push('---');
  parts.push(`*Generated by EPD Advisor — ${persona.name} persona (custom)*`);
  return parts.join('\n');
}

/**
 * Create a custom persona runner.
 *
 * @param {object} persona - Validated persona definition from custom-personas-config.js
 * @returns {{ runCycle: Function }}
 */
export function createCustomPersona(persona) {
  /**
   * Run one cycle of the custom persona against all eligible projects.
   *
   * @param {object} opts
   * @param {object} opts.db - Firestore Admin instance
   * @param {object} opts.projectService - Project service
   * @param {Function} opts.makeTicketService - Factory (projectId) => ticketService
   * @param {Function} [opts.onActivity] - Activity reporting callback
   * @param {string|null} [opts.soulPrompt] - Soul prompt override from Firestore
   * @param {string|null} [opts.focusPrompt] - Optional on-demand focus prompt (appended after delimiter)
   * @param {string|null} [opts.scopeText] - Optional focus scope for this run (DK-367) — injected as [SCOPE:] block
   * @param {string|null} [opts.triggerProjectId] - If set, only run against this project
   * @returns {Promise<{ ticketsCreated: number, lastActivity: string }>}
   */
  async function runCycle({ db, projectService, makeTicketService, onActivity, soulPrompt, focusPrompt, scopeText, triggerProjectId = null, projectScreenshotConfigs = {}, projectConfigs = {} }) {
    const report = (msg) => {
      log(persona.id, msg);
      if (onActivity) onActivity(msg);
    };

    const baseSystemPrompt = soulPrompt || persona.systemPrompt;
    // DK-367: Inject scope as a clearly delimited block early in the system prompt.
    const effectiveSystemPrompt = scopeText
      ? `${baseSystemPrompt}\n\n[SCOPE: ${scopeText}]\nFocus your analysis exclusively on the scope defined above.`
      : baseSystemPrompt;

    const projects = await projectService.list();
    const allEligible = projects.filter(p => p.advisorContext?.trim());
    // If persona has a projects scope, filter to only those projects
    const scopedEligible = persona.projects
      ? allEligible.filter(p => persona.projects.includes(p.id))
      : allEligible;
    const eligible = triggerProjectId
      ? scopedEligible.filter(p => p.id === triggerProjectId)
      : scopedEligible;
    if (triggerProjectId && eligible.length === 0) {
      const targetProject = projects.find(p => p.id === triggerProjectId);
      if (targetProject) {
        report(`Project "${triggerProjectId}" has no advisorContext set — add context in project settings to enable advisor`);
      } else {
        report(`Project "${triggerProjectId}" not found — skipping`);
      }
    } else if (!triggerProjectId && allEligible.length === 0 && projects.length > 0) {
      const projectIds = projects.map(p => p.id).join(', ');
      report(`No projects have advisorContext set (found: ${projectIds}) — add context in project settings to enable advisor`);
    } else {
      report(`Found ${eligible.length} project(s) with advisorContext${triggerProjectId ? ` (filtered to: ${triggerProjectId})` : ''}`);
    }

    let totalTickets = 0;
    const activities = [];

    // If no projects are eligible due to missing advisorContext, record that in activities
    // so the UI shows a clear message rather than a generic "No eligible projects".
    if (eligible.length === 0 && projects.length > 0 && !triggerProjectId) {
      activities.push('No projects have advisorContext set — add context in project settings to enable advisor');
    } else if (eligible.length === 0 && triggerProjectId) {
      const targetProject = projects.find(p => p.id === triggerProjectId);
      activities.push(targetProject
        ? `Project "${triggerProjectId}" has no advisorContext set — add context in project settings`
        : `Project "${triggerProjectId}" not found`);
    }

    for (const project of eligible) {
      let cycleStatus = 'ok';
      let cycleError = null;
      let proposalsCreated = 0;

      // DK-189: structured run logger (replaces writeRunRecord + writeRunLog)
      const runLogger = createRunLogger({ db, persona: persona.id, projectId: project.id, scopeText: scopeText || null });

      try {
        report(`[${project.id}] Starting…`);
        const ticketService = makeTicketService(project.id);

        // Fetch rejection history for this project
        const rejections = await fetchRejections(db, project.id);
        if (rejections.length > 0) {
          report(`[${project.id}] ${rejections.length} rejection(s) in history`);
        }
        const rejectionHistoryBlock = formatRejectionHistory(rejections, persona.id);

        const sanitizedFocusPrompt = sanitizeFocusPrompt(focusPrompt);

        // Scan source files if the project has repoPath + scanPaths configured
        const pCfg = projectConfigs[project.id] || {};
        let sourceBlock = '';
        if (pCfg.repoPath && pCfg.scanPaths?.length) {
          try {
            const files = await scanFiles(pCfg.repoPath, pCfg.scanPaths);
            if (files.length > 0) {
              report(`[${project.id}] Scanned ${files.length} source file(s)`);
              sourceBlock = '\n\n## Source Files\n' + formatFileBatch(files);
              if (runLogger) {
                for (const f of files) runLogger.addScanned(f.path);
              }
            }
          } catch (scanErr) {
            report(`[${project.id}] File scan failed: ${scanErr.message}`);
          }
        }

        // Run playtest if persona has playtest: true and project has a playtest command
        let playtestBlock = '';
        if (persona.playtest && pCfg.repoPath && pCfg.screenshotCommand) {
          try {
            // Read playtestRuns override from Firestore persona state, fall back to config default
            let runs = persona.playtestRuns || 10;
            try {
              const personaDoc = await db.collection('advisor').doc(persona.id).get();
              const fsRuns = personaDoc.exists && personaDoc.data()?.playtestRuns;
              if (Number.isFinite(fsRuns) && fsRuns >= 1 && fsRuns <= 50) runs = fsRuns;
            } catch { /* use config default */ }

            // Build the playtest command — replace --runs N if present, otherwise append
            let cmd = pCfg.screenshotCommand;
            if (/--runs\s+\d+/.test(cmd)) {
              cmd = cmd.replace(/--runs\s+\d+/, `--runs ${runs}`);
            } else {
              cmd = `${cmd} --runs ${runs}`;
            }
            report(`[${project.id}] Running playtest (${runs} run(s))…`);
            const playtestOutput = execSync(cmd, {
              cwd: pCfg.repoPath,
              timeout: 10 * 60 * 1000,
              encoding: 'utf8',
              stdio: ['pipe', 'pipe', 'pipe'],
            });
            // Extract JSON from output (script may print non-JSON preamble)
            const jsonStart = playtestOutput.indexOf('{');
            if (jsonStart >= 0) {
              const playtestJson = playtestOutput.slice(jsonStart);
              try {
                JSON.parse(playtestJson); // validate
                playtestBlock = '\n\n## Playtest Results\n```json\n' + playtestJson.trim() + '\n```';
                report(`[${project.id}] Playtest complete`);
              } catch {
                report(`[${project.id}] Playtest output was not valid JSON`);
              }
            } else {
              report(`[${project.id}] Playtest produced no JSON output`);
            }
          } catch (ptErr) {
            report(`[${project.id}] Playtest failed: ${ptErr.message?.slice(0, 150)}`);
          }
        }

        const userPrompt = buildPrompt(persona, project.advisorContext, rejectionHistoryBlock, sanitizedFocusPrompt) + sourceBlock + playtestBlock;

        let raw;
        const askOpts = { model: persona.model, timeoutMs: 10 * 60 * 1000 };
        const ssConfig = persona.visual && projectScreenshotConfigs[project.id];
        if (ssConfig) {
          try {
            const imageBuffers = await getScreenshots(project.id, ssConfig);
            if (imageBuffers.length > 0) {
              report(`[${project.id}] Using ${imageBuffers.length} screenshot(s)`);
              raw = await askWithImages(effectiveSystemPrompt, imageBuffers, userPrompt, askOpts);
            } else {
              report(`[${project.id}] No screenshots found — text-only fallback`);
              raw = await ask(effectiveSystemPrompt, userPrompt, askOpts);
            }
          } catch (ssErr) {
            report(`[${project.id}] Screenshot capture failed: ${ssErr.message} — text-only fallback`);
            raw = await ask(effectiveSystemPrompt, userPrompt, askOpts);
          }
        } else {
          raw = await ask(effectiveSystemPrompt, userPrompt, askOpts);
        }
        const proposals = parseProposals(raw, persona.id);

        report(`[${project.id}] ${proposals.length} proposal(s) from Claude`);

        if (proposals.length === 0) {
          cycleStatus = 'quiet';
          activities.push(`${project.id}: no issues found`);
          continue;
        }

        // Use listStubs() for dedup — only needs title/status/snoozedUntil/id,
        // not full ticket documents. Falls back to listAll() for older service instances.
        const existingTickets = await (ticketService.listStubs || ticketService.listAll).call(ticketService);
        let created = 0;

        for (const proposal of proposals) {
          if (!proposal.title || !proposal.description) continue;

          const ticketTitle = `[${persona.name}] ${proposal.title}`;
          const { isDuplicate, matchTitle, matchId, matchedKeywords } = checkDuplicate(existingTickets, ticketTitle);
          if (isDuplicate) {
            log(persona.id, `[${project.id}] Skip (duplicate of "${matchTitle}"): ${proposal.title}`);
            const matchedTicket = existingTickets.find(t => t.title === matchTitle);
            runLogger.addRejected({ title: proposal.title, reason: 'duplicate', matchedTicketId: matchId });
            // DK-189: record structured dedup hit for the run log drawer
            if (matchId && matchedKeywords) {
              runLogger.addDeduped({ summary: matchedKeywords, blockedBy: matchId });
            }
            continue;
          }

          const { isSuppressed, matchTitle: rejMatchTitle, matchCount } = checkRejectionMatch(rejections, ticketTitle);
          if (isSuppressed) {
            log(persona.id, `[${project.id}] Skip (matches ${matchCount} rejection(s), similar to "${rejMatchTitle}"): ${proposal.title}`);
            runLogger.addRejected({ title: proposal.title, reason: 'threshold' });
            runLogger.addFiltered(FILTER_REASONS.REJECTION_MATCH);
            continue;
          }

          const type = proposal.type === 'feature' ? 'feature' : 'bug';
          const ticketDescription = buildTicketDescription(proposal, persona);
          // Respect yoloMode: if enabled on this project, create tickets as 'open'
          // so they go directly to the backlog without requiring manual triage.
          const initialStatus = project.yoloMode ? 'open' : 'proposed';
          // DK-189: include advisorRunId for ticket attribution back to this run
          const advisorRunId = runLogger.getRunId();
          const ticket = await ticketService.add({
            type,
            title: ticketTitle,
            description: ticketDescription,
            userId: null,
            userEmail: 'advisor@docket.app',
            status: initialStatus,
            advisorPersona: persona.id,
            ...(advisorRunId ? { advisorRunId } : {}),
          });

          // Assign theme clusters (server-side, post-create)
          try {
            const clusterIds = await assignClusters({
              db,
              projectId: project.id,
              title: ticketTitle,
              description: ticketDescription,
            });
            if (clusterIds.length > 0) {
              await ticketService.update(ticket.id, { clusterIds });
              log(persona.id, `[${project.id}] Clustered ${ticket.ticketId} → [${clusterIds.join(', ')}]`);
            }
          } catch (err) {
            log(persona.id, `[${project.id}] Cluster assignment failed for ${ticket.ticketId}: ${err.message}`);
          }

          log(persona.id, `[${project.id}] Created ${ticket.ticketId}: ${proposal.title}`);
          runLogger.addCreated(ticket.id);
          created++;
          proposalsCreated++;
          existingTickets.push({ title: ticket.title, status: 'open' });

          // Async score — fires after ticket write, does not block creation.
          // If scoring fails, the ticket remains with null scores (handled gracefully in UI).
          const ticketContent = `${ticket.title}\n\n${ticketDescription}`;
          scoreProposal(ticketContent).then(scores => {
            if (!scores) {
              log(persona.id, `[${project.id}] Scoring returned null for ${ticket.ticketId} — skipping`);
              return;
            }
            return ticketService.updateScore(ticket.id, scores).then(() => {
              log(persona.id, `[${project.id}] Scored ${ticket.ticketId}: impact=${scores.impact} effort=${scores.effort}`);
            });
          }).catch(err => {
            log(persona.id, `[${project.id}] Async score write failed for ${ticket.ticketId}: ${err.message}`);
          });
        }

        totalTickets += created;
        cycleStatus = created > 0 ? 'ok' : 'quiet';
        activities.push(`${project.id}: ${created > 0 ? `${created} ticket(s) created` : 'no new issues'}`);
        report(`[${project.id}] Cycle complete — ${created} ticket(s) created`);
      } catch (err) {
        cycleStatus = 'error';
        cycleError = sanitizeError(err);
        activities.push(`${project.id}: error — ${err.message || 'unknown'}`);
        log(persona.id, `[${project.id}] Cycle error: ${err.message}`);
        if (process.env.DEBUG) console.error(err);
      } finally {
        // DK-189: flush structured run log (replaces writeRunRecord + writeRunLog)
        await runLogger.flush(cycleStatus === 'ok' || cycleStatus === 'quiet' ? 'completed' : 'failed', cycleError);
      }
    }

    return {
      ticketsCreated: totalTickets,
      lastActivity: activities.length > 0 ? activities.join(' | ') : 'No eligible projects',
    };
  }

  return { runCycle };
}
